const bookingData = {
    
        active: [
            {
        id: 1,
        studentName: 'Іван',
        studentSurname: 'Петренко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380123456789',
        date: '15-05-2024',
        time: '10:00',
        venue: 'Онлайн',
        subject: 'Математика',
        price: '200 грн',
    },
    {
        id: 2,
        studentName: 'Олена',
        studentSurname: 'Ковальчук',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380987654321',
        date: '20-05-2024',
        time: '14:00',
        venue: 'Онлайн',
        subject: 'Англійська мова',
        price: '250 грн',
    },
    {
        id: 3,
        studentName: 'Марина',
        studentSurname: 'Сидоренко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380555555555',
        date: '25-05-2024',
        time: '16:00',
        venue: 'Онлайн',
        subject: 'Фізика',
        price: '300 грн',
    },
    {
        id: 4,
        studentName: 'Андрій',
        studentSurname: 'Коваленко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380333333333',
        date: '30-05-2024',
        time: '12:00',
        venue: 'Онлайн',
        subject: 'Історія',
        price: '180 грн',
    },
    {
        id: 5,
        studentName: 'Олексій',
        studentSurname: 'Шевченко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380444444444',
        date: '05-06-2024',
        time: '11:00',
        venue: 'Онлайн',
        subject: 'Хімія',
        price: '270 грн',
        },
    {
        id: 6,
        studentName: 'Антон',
        studentSurname: 'Сидоров',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390922222222',
        date: '30-06-2023',
        time: '10:00',
        venue: 'Онлайн',
        subject: 'Хімія',
        price: '320 грн',
    }
        ],
        inactive: [
           {
        id: 1,
        studentName: 'Стефан',
        studentSurname: 'Мироненко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390966466666',
        date: '10-10-2023',
        time: '12:00',
        venue: 'Онлайн',
        subject: 'Геометрія',
        price: '300 грн',
    },
    {
        id: 2,
        studentName: 'Ольга',
        studentSurname: 'Іванова',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390955555555',
        date: '15-09-2023',
        time: '14:30',
        venue: 'Онлайн',
        subject: 'Література',
        price: '250 грн',
    },
    {
        id: 3,
        studentName: 'Михайло',
        studentSurname: 'Петров',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390944444444',
        date: '20-08-2023',
        time: '16:00',
        venue: 'Онлайн',
        subject: 'Фізика',
        price: '280 грн',
    },
    {
        id: 4,
        studentName: 'Ірина',
        studentSurname: 'Ковалева',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390933333333',
        date: '25-07-2023',
        time: '11:00',
        venue: 'Онлайн',
        subject: 'Історія',
        price: '200 грн',
    },
    {
        id: 5,
        studentName: 'Антон',
        studentSurname: 'Сидоров',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390922222222',
        date: '30-06-2023',
        time: '10:00',
        venue: 'Онлайн',
        subject: 'Хімія',
        price: '320 грн',
    }
        ],
  
}

export default bookingData;
