const bookingData = {
    
        active: [
            {
        id: 1,
        studentName: 'Іван',
        studentSurname: 'Петренко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380123456789',
        date: '15-05-2024',
        time: '10:00',
        venue: 'Онлайн',
        subject: 'Математика',
        price: '200 грн',
    },
    {
        id: 2,
        studentName: 'Олена',
        studentSurname: 'Ковальчук',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380987654321',
        date: '20-05-2024',
        time: '14:00',
        venue: 'Онлайн',
        subject: 'Англійська мова',
        price: '250 грн',
    },
    {
        id: 3,
        studentName: 'Марина',
        studentSurname: 'Сидоренко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380555555555',
        date: '25-05-2024',
        time: '16:00',
        venue: 'Онлайн',
        subject: 'Фізика',
        price: '300 грн',
    },
    {
        id: 4,
        studentName: 'Андрій',
        studentSurname: 'Коваленко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380333333333',
        date: '30-05-2024',
        time: '12:00',
        venue: 'Онлайн',
        subject: 'Історія',
        price: '180 грн',
    },
    {
        id: 5,
        studentName: 'Олексій',
        studentSurname: 'Шевченко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+380444444444',
        date: '05-06-2024',
        time: '11:00',
        venue: 'Онлайн',
        subject: 'Хімія',
        price: '270 грн',
        },
      { id: 7,
      studentName: 'Марія',
      studentSurname: 'Коваленко',
      studentPhoto: require( '../../../assets/home/our-teachers/2.png' ),
      studentPhone: '+380987654321',
      date: '16-05-2024',
      time: '12:00',
      venue: 'Офлайн',
      subject: 'Фізика',
      price: '250 грн',
    },
    {
      id: 8,
      studentName: 'Олександр',
      studentSurname: 'Сидоренко',
      studentPhoto: require( '../../../assets/home/our-teachers/3.png' ),
      studentPhone: '+380555555555',
      date: '17-05-2024',
      time: '14:00',
      venue: 'Онлайн',
      subject: 'Історія',
      price: '180 грн',
    },
    {
      id: 9,
      studentName: 'Анна',
      studentSurname: 'Іванова',
      studentPhoto: require( '../../../assets/home/our-teachers/4.png' ),
      studentPhone: '+380666666666',
      date: '18-05-2024',
      time: '16:00',
      venue: 'Офлайн',
      subject: 'Англійська',
      price: '220 грн',
    },
    {
      id: 10,
      studentName: 'Петро',
      studentSurname: 'Григоренко',
      studentPhoto: require( '../../../assets/home/our-teachers/5.png' ),
      studentPhone: '+380777777777',
      date: '19-05-2024',
      time: '18:00',
      venue: 'Онлайн',
      subject: 'Біологія',
      price: '190 грн',
    },
    {
      id: 11,
      studentName: 'Софія',
      studentSurname: 'Попова',
      studentPhoto: require( '../../../assets/home/our-teachers/6.png' ),
      studentPhone: '+380888888888',
      date: '20-05-2024',
      time: '10:00',
      venue: 'Офлайн',
      subject: 'Хімія',
      price: '230 грн',
    },
    {
      id: 12,
      studentName: 'Олег',
      studentSurname: 'Кузьменко',
      studentPhoto: require( '../../../assets/home/our-teachers/7.png' ),
      studentPhone: '+380999999999',
      date: '21-05-2024',
      time: '12:00',
      venue: 'Онлайн',
      subject: 'Географія',
      price: '210 грн',
    },
    {
      id: 13,
      studentName: 'Наталія',
      studentSurname: 'Біленька',
      studentPhoto: require( '../../../assets/home/our-teachers/8.png' ),
      studentPhone: '+380123123123',
      date: '22-05-2024',
      time: '14:00',
      venue: 'Офлайн',
      subject: 'Література',
      price: '240 грн',
    },
    {
      id: 14,
      studentName: 'Максим',
      studentSurname: 'Семенченко',
      studentPhoto: require( '../../../assets/home/our-teachers/9.png' ),
      studentPhone: '+380456456456',
      date: '23-05-2024',
      time: '16:00',
      venue: 'Онлайн',
      subject: 'Інформатика',
      price: '200 грн',
    },
    {
      id: 15,
      studentName: 'Олена',
      studentSurname: 'Кравченко',
      studentPhoto: require( '../../../assets/home/our-teachers/10.png' ),
      studentPhone: '+380789789789',
      date: '24-05-2024',
      time: '18:00',
      venue: 'Офлайн',
      subject: 'Фізкультура',
      price: '180 грн',
    },
        ],
        inactive: [
           {
        id: 1,
        studentName: 'Стефан',
        studentSurname: 'Мироненко',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390966466666',
        date: '10-10-2023',
        time: '12:00',
        venue: 'Онлайн',
        subject: 'Геометрія',
        price: '300 грн',
    },
    {
        id: 2,
        studentName: 'Ольга',
        studentSurname: 'Іванова',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390955555555',
        date: '15-09-2023',
        time: '14:30',
        venue: 'Онлайн',
        subject: 'Література',
        price: '250 грн',
    },
    {
        id: 3,
        studentName: 'Михайло',
        studentSurname: 'Петров',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390944444444',
        date: '20-08-2023',
        time: '16:00',
        venue: 'Онлайн',
        subject: 'Фізика',
        price: '280 грн',
    },
    {
        id: 4,
        studentName: 'Ірина',
        studentSurname: 'Ковалева',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390933333333',
        date: '25-07-2023',
        time: '11:00',
        venue: 'Онлайн',
        subject: 'Історія',
        price: '200 грн',
    },
    {
        id: 5,
        studentName: 'Антон',
        studentSurname: 'Сидоров',
        studentPhoto: require( '../../../assets/home/our-teachers/1.png' ),
        studentPhone: '+390922222222',
        date: '30-06-2023',
        time: '10:00',
        venue: 'Онлайн',
        subject: 'Хімія',
        price: '320 грн',
    }
        ],
  
}

export default bookingData;
