const dataSubject = [
  {
    id: 1,
    nameLesson: 'Німецька мова',
    country: 'Україна',
    sity: 'Київ',
    teacher: 'Name 1',
    online: false,
    rating: 10,
  },
  {
    id: 2,
    nameLesson: 'Йога',
    country: 'Німеччина',
    sity: 'Гамбург',
    teacher: 'Name 2',
    online: false,
    rating: 10,
  },
  {
    id: 3,
    nameLesson: 'Гра на гітарі',
    country: 'Канада',
    sity: 'Торонто',
    teacher: 'Name 3',
    online: false,
    rating: 10,
  },
  {
    id: 4,
    nameLesson: 'Англійська мова',
    country: 'Польща',
    sity: 'Варшава',
    teacher: 'Name 4',
    online: false,
    rating: 10,
  },
  {
    id: 5,
    nameLesson: 'Французька мова',
    country: 'Велика Британія',
    sity: 'Лондон',
    teacher: 'Name 5',
    online: false,
    rating: 10,
  },
  {
    id: 6,
    nameLesson: 'Польська мова',
    country: 'Чехія',
    sity: 'Прага',
    teacher: 'Name 6',
    online: false,
    rating: 10,
  },
  {
    id: 7,
    nameLesson: 'Чешська мова',
    country: 'Україна',
    sity: 'Київ',
    teacher: 'Name 7',
    online: false,
    rating: 10,
  },
  {
    id: 8,
    nameLesson: 'Різьба по дереву',
    country: 'Німеччина',
    sity: 'Берлін',
    teacher: 'Name 8',
    online: false,
    rating: 10,
  },
  {
    id: 9,
    nameLesson: 'Математика',
    country: 'Чехія',
    sity: 'Карлови Вари',
    teacher: 'Name 9',
    online: false,
    rating: 10,
  },
  {
    id: 10,
    nameLesson: 'Фітнес',
    country: 'США',
    sity: 'Чікаго',
    teacher: 'Name 10',
    online: false,
    rating: 10,
  },
  {
    id: 11,
    nameLesson: 'Стрейчинг',
    country: 'Україна',
    sity: 'Львів',
    teacher: 'Name 11',
    online: false,
    rating: 10,
  },
  {
    id: 12,
    nameLesson: 'Брейкденс',
    country: 'Німеччина',
    sity: 'Гамбург',
    teacher: 'Name 12',
    online: false,
    rating: 10,
  },
  {
    id: 13,
    nameLesson: 'Ораторське мистецтво',
    country: 'Чехія',
    sity: 'Прага',
    teacher: 'Name 13',
    online: false,
    rating: 10,
  },
  {
    id: 14,
    nameLesson: 'Просування блогу',
    country: 'Україна',
    sity: 'Київ',
    teacher: 'Name 14',
    online: false,
    rating: 10,
  },
  {
    id: 15,
    nameLesson: 'Вокал',
    country: 'Латвія',
    sity: 'Ріга',
    teacher: 'Name 15',
    online: false,
    rating: 10,
  },
  {
    id: 16,
    nameLesson: 'Малювання фарбами',
    country: 'Франція',
    sity: 'Париж',
    teacher: 'Name 16',
    online: false,
    rating: 10,
  },
  {
    id: 17,
    nameLesson: 'Акторська майстерність',
    country: 'Польща',
    sity: 'Краків',
    teacher: 'Name 17',
    online: false,
    rating: 10,
  },
  {
    id: 18,
    nameLesson: 'Ліпка з глини',
    country: 'Чехія',
    sity: 'Прага',
    teacher: 'Name 18',
    online: false,
    rating: 10,
  },
  {
    id: 19,
    nameLesson: 'Фітнес',
    country: 'Україна',
    sity: 'Чернігів',
    teacher: 'Name 19',
    online: false,
    rating: 10,
  },
  {
    id: 20,
    nameLesson: 'Стрейчинг',
    country: 'Німеччина',
    sity: 'Берлін',
    teacher: 'Name 20',
    online: false,
    rating: 10,
  },
  {
    id: 21,
    nameLesson: 'Брейкденс',
    country: 'Велика Британія',
    sity: 'Лондон',
    teacher: 'Name 21',
    online: false,
    rating: 10,
  },
  {
    id: 22,
    nameLesson: 'Ораторське мистецтво',
    country: 'Чехія',
    sity: 'Брно',
    teacher: 'Name 22',
    online: false,
    rating: 10,
  },
  {
    id: 23,
    nameLesson: 'Просування блогу',
    country: 'Німеччина',
    sity: 'Берлін',
    teacher: 'Name 23',
    online: false,
    rating: 10,
  },
  {
    id: 24,
    nameLesson: 'Вокал',
    country: 'Україна',
    sity: 'Львів',
    teacher: 'Name 24',
    online: false,
    rating: 10,
  },
  {
    id: 25,
    nameLesson: 'Англійська література',
    country: 'Чехія',
    sity: 'Прага',
    teacher: 'Name 25',
    online: false,
    rating: 10,
  },
  {
    id: 26,
    nameLesson: 'Німецька мова',
    country: 'Україна',
    sity: 'Львів',
    teacher: 'Name 26',
    online: false,
    rating: 10,
  },
];

export default dataSubject;
