export const backendData = [
    {
      id: 1,
      teacherName: 'Олександр',
      teacherSurname: 'Олешко',
      teacherPhoto: require( '../../../assets/home/our-teachers/1.png' ),
      teacherPhone: '+39 096 666 66 66',
      date: '28.10.23',
      time: '9:00',
      venue: 'Онлайн',
      classes: 'Німецька мова',
      price: '300 грн.',
    },
    {
      id: 2,
      teacherName: 'Степанида',
      teacherSurname: 'Прекрасна',
      teacherPhoto: require( '../../../assets/home/our-teachers/19.png' ),
      teacherPhone: '+39 096 666 66 44',
      date: '29.10.23',
      time: '10:00',
      venue: 'Онлайн',
      classes: 'Історія',
      price: '400 грн.',
    },
    {
      id: 3,
      teacherName: 'Вікентій',
      teacherSurname: 'Розумний',
      teacherPhoto: require( '../../../assets/home/our-teachers/2.png' ),
      teacherPhone: '+39 096 666 55 66',
      date: '30.10.23',
      time: '11:00',
      venue: 'Онлайн',
      classes: 'ОБЖ',
      price: '250 грн.',
  },
];
