export const backendDataActive = [
    {
      id: 1,
      teacherName: 'Стефан',
      teacherSurname: 'Мироненко',
      teacherPhoto: require( '../../../assets/home/our-teachers/16.png' ),
      teacherPhone: '+39 096 646 66 66',
      date: '10.10.23',
      time: '12:00',
      venue: 'Онлайн',
      classes: 'Геометрія',
      price: '300 грн.',
    },
    {
      id: 2,
      teacherName: 'Євстахія',
      teacherSurname: 'Свідома',
      teacherPhoto: require( '../../../assets/home/our-teachers/12.png' ),
      teacherPhone: '+39 095 666 66 44',
      date: '11.10.23',
      time: '13:00',
      venue: 'Онлайн',
      classes: 'Хімія',
      price: '350 грн.',
    },
    {
      id: 3,
      teacherName: 'Дзвенислава',
      teacherSurname: 'Тиходіл',
      teacherPhoto: require( '../../../assets/home/our-teachers/14.png' ),
      teacherPhone: '+39 096 667 54 66',
      date: '12.10.23',
      time: '14:00',
      venue: 'Онлайн',
      classes: 'Співи',
      price: '250 грн.',
  },
];
